TestCaseBusinessSolutions/Controllers/ProviderController.cs
using Microsoft.AspNetCore.Mvc;
using TestCaseBusinessSolutions.DataAccess.Data;
using TestCaseBusinessSolutions.DataAccess.Repository.IRepository;
using TestCaseBusinessSolutions.Models;
using System;

namespace TestCaseBusinessSolutions.Web.Controllers
{
    public class ProviderController : Controller
    {
        
        private readonly IUnitOfWork _unitOfWork;
        public ProviderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Provider> objProviderList = _unitOfWork.Provider.GetAll();
            return View(objProviderList);
        }
        [ActionName("Create")]
        public IActionResult Create()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(Provider obj)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.Provider.Add(obj);
                _unitOfWork.Save();
                TempData["sucсess"] = "Category Created sucessfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //GET

        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            //var categoryFromDb= _db.Categories.Find(id);
            var ProviderFromDbFirst = _unitOfWork.Provider.GetFirstOrDefault(u => u.Id == id);
            if (ProviderFromDbFirst == null)
            {
                return NotFound();
            }
            return View(ProviderFromDbFirst);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Provider obj)
        {
            
            if (ModelState.IsValid)
            {
                _unitOfWork.Provider.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Category updated sucessfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var providerFromDbFirst = _unitOfWork.Provider.GetFirstOrDefault(u => u.Id == id);
            if (providerFromDbFirst == null)
            {
                return NotFound();
            }
            return View(providerFromDbFirst);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _unitOfWork.Provider.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Provider.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Category deleted sucessfully";
            return RedirectToAction("Index");


        }
    }
}

TestCaseBusinessSolutions/Views/Provider/Create.cshtml
@using TestCaseBusinessSolutions.Models

@model Provider

<form method="post" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Provider</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" id="NameUpload" class="text-danger"></span>
        </div>
        
          
        
          <button type="submit" onclick="return ValidateInput()" class="btn btn-primary" style="width:150px">Create</button>   
        
        <a asp-controller="Provider"  asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>
@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    
}

TestCaseBusinessSolutions/Views/Provider/Delete.cshtml
@using TestCaseBusinessSolutions.Models


    @model Provider

    <form method="post" asp-action="DeletePost">
        <input asp-for="Id" hidden />
        <div class="border p-3 mt-4">
            <div class="row pb-2">
                <h2 class="text-primary">Delete Provider</h2>
                <hr />
            </div>
            @*<div asp-validation-summary="All"></div>*@
            <div class="mb-3">
                <label asp-for="Name"></label>
                <input asp-for="Name" disabled class="form-control" />
            
            </div>
           
            <button type="submit" class="btn btn-primary" style="width:150px">Delete</button>
            <a asp-controller="Provider" asp-action="Index" class="btn btn-primary" style="width:150px">
                Back to list
            </a>
        </div>
    </form>
    @section Scripts
    {
        @{
            <partial name="_ValidationScriptsPartial" />
        }
    }

TestCaseBusinessSolutions/Views/Provider/Edit.cshtml
@using TestCaseBusinessSolutions.Models

@model Provider

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Provider</h2>
            <hr />
        </div>
       @* <div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Provider" asp-action="Index" class="btn btn-primary" style="width:150px">
            Back to list
        </a>
    </div>
</form>
@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

TestCaseBusinessSolutions/Views/Provider/Index.cshtml
@using TestCaseBusinessSolutions.Models;
@model IEnumerable<Provider> 
@{
    ViewData["Title"] = "Index";
}
<div class="container p-3">
<div class="row pt-4">
<div class="col-6">
    <h2 class="text-primary">
        Provider List
    </h2>
</div>
<div class="col-6 text-end">
    <a  asp-controller="Provider"  asp-action="Create"   class="btn btn-primary">
       <i class="bi bi-plus-circle"></i>&nbsp;Create New Provider
    </a>
</div>
</div>
<br /> <br />
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Provider Name
            </th>
           
           @* <th>

            </th>
             <th>

            </th>*@
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.Name
                </td>
               
                <td>
                    <div class="w-75 h-75 btn-group" role="group">
                        <a asp-controller="Provider" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2" ><i class="bi bi-pencil-square"></i>Edit</a>
                        <a asp-controller="Provider" asp-action="Delete"  asp-route-id="@obj.Id" class="btn btn-danger btn-primary mx-2"><i class="bi bi-trash"></i>Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>