TestCaseBusinessSolutions/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TestCaseBusinessSolutions.DataAccess.Repository.IRepository;
using TestCaseBusinessSolutions.Models;
using TestCaseBusinessSolutions.Models.ViewModels;

namespace TestCaseBusinessSolutions.Web.Controllers
{
    public class OrderController:Controller
    {
        private readonly IUnitOfWork _unitOfWork;
     
        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Upsert(int? id)
        {
            OrderVM orderVM = new()
            {
                Order = new(),
                ProviderList = _unitOfWork.Provider.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                   
                }),
            

            };
            if (id == 0 || id == null)
            {

                return View(orderVM);
            }
            else
            {
                orderVM.Order = _unitOfWork.Order.GetFirstOrDefault(u => u.Id == id);
                return View(orderVM);
            }


        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Order obj, IFormFile? file)
        {

            if (ModelState.IsValid)
            {

                if (obj.Id == 0)
                {
                    _unitOfWork.Order.Add(obj);
                    TempData["success"] = "Product  created sucessfully";
                }
                else
                {
                    _unitOfWork.Order.Update(obj);
                    TempData["success"] = "Product  updated sucessfully";
                }
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(obj);

        }
        public IActionResult Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var orderFromDbFirst = _unitOfWork.Order.GetFirstOrDefault(u => u.Id == id);
            if (orderFromDbFirst == null)
            {
                return NotFound();
            }
            return View(orderFromDbFirst);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _unitOfWork.Order.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Order.Remove(obj);
            _unitOfWork.Save();
            return RedirectToAction("Index");


        }

        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {

            IEnumerable<Order> orders;
            
            orders = _unitOfWork.Order.GetAll(includeProperties: "Provider");
            
            
           
            
            return new JsonResult(new { data = orders });
        }
        #endregion
    }
}

TestCaseBusinessSolutions/Controllers/OrderItemController.cs
using Microsoft.AspNetCore.Mvc;
using TestCaseBusinessSolutions.DataAccess.Repository.IRepository;
using TestCaseBusinessSolutions.Models;
using TestCaseBusinessSolutions.Models.ViewModels;

namespace TestCaseBusinessSolutions.Web.Controllers
{
    public class OrderItemController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public OrderItemController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upsert(int? id)
        {
            OrderItem orderItem = new();
            
            if (id == 0 || id == null)
            {

                return View(orderItem);
            }
            else
            {
                orderItem = _unitOfWork.OrderItem.GetFirstOrDefault(u => u.Id == id);
                return View(orderItem);
            }


        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(OrderItem obj)
        {

            //if (ModelState.IsValid)
            //{

                if (obj.Id == 0)
                {
                    _unitOfWork.OrderItem.Add(obj);
                    TempData["success"] = "Product  created sucessfully";
                }
                else
                {
                    _unitOfWork.OrderItem.Update(obj);
                    TempData["success"] = "Product  updated sucessfully";
                }
                _unitOfWork.Save();
                return RedirectPermanent("/Home/Index");
            //}
            //return View(obj);

        }
        public IActionResult Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var orderItemFromDbFirst = _unitOfWork.OrderItem.GetFirstOrDefault(u => u.Id == id);
            if (orderItemFromDbFirst == null)
            {
                return NotFound();
            }
            return View(orderItemFromDbFirst);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _unitOfWork.OrderItem.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.OrderItem.Remove(obj);
            _unitOfWork.Save();
            return RedirectPermanent("/Home/Index");


        }

        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {

            IEnumerable<OrderItem> orderItems;

            orderItems = _unitOfWork.OrderItem.GetAll();




            return new JsonResult(new { data = orderItems });
        }
        #endregion
    }
}

TestCaseBusinessSolutions/Views/Order/Delete.cshtml
@using TestCaseBusinessSolutions.Models


    @model Order

    <form method="post" asp-action="DeletePost">
        <input asp-for="Id" hidden />
        <div class="border p-3 mt-4">
            <div class="row pb-2">
                <h2 class="text-primary">Delete Order</h2>
                <hr />
            </div>
            @*<div asp-validation-summary="All"></div>*@
            <div class="mb-3">
                <label asp-for="Number"></label>
                <input asp-for="Number" disabled class="form-control" />
            
            </div>
             <div class="mb-3">
                <label asp-for="Date"></label>
                <input asp-for="Date" disabled class="form-control" />
            
            </div>
        
           
            <button type="submit" class="btn btn-primary" style="width:150px">Delete</button>
            <a asp-controller="Home" asp-action="Index" class="btn btn-primary" style="width:150px">
                Back to list
            </a>
        </div>
    </form>
    @section Scripts
    {
        @{
            <partial name="_ValidationScriptsPartial" />
        }
    }

TestCaseBusinessSolutions/Views/Order/Upsert.cshtml
@model TestCaseBusinessSolutions.Models.ViewModels.OrderVM
<form method="post" asp-action="Upsert" enctype="multipart/form-data">
    <input asp-for="Order.Id" hidden />
     <div class="row">
         <div class="col-10">
                 <div class="border p-3 mt-4 row" >
            <div class="row col-12 pb-2">
                <h2 class="text-primary">@(Model.Order.Id!=0?"Update":"Create") Order</h2>
                <hr />
            </div>
            
            <div class="mb-3">
                <label asp-for="Order.Number"></label>
                <input asp-for="Order.Number" class="form-control" />
                <span asp-validation-for="Order.Number" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Order.Date"></label>
                <input asp-for="Order.Date" class="form-control" />
                <span asp-validation-for="Order.Date" class="text-danger"></span>
            </div>
            
            <div class="mb-3 col-6">
                <label asp-for="Order.ProviderId"></label>
                <select asp-for="Order.ProviderId" asp-items="@Model.ProviderList" class="form-select">
                    <option disabled-selected>--Select Provider--</option>
                </select>
                <span asp-validation-for="Order.Provider" class="text-danger"></span>
            </div>
            <div class="row pt-4">
            <div class="col-6 text-end">
            <h2 class="text-primary">
                Product List
            </h2>
             </div>
            <div class="col-6 text-end">
            <a  asp-controller="OrderItem" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>&nbsp;Create New Product
            </a>
              </div>
                </div>
            <table class="table table-bordered table-striped" id="tblData" style="width:100%">
        <thead>
            <tr>
             
                <th>
                    Name
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    Unit
                </th>
                
                <th>
                    Update
                </th>
                <th>
                    Delete
                </th>
            </tr>
        </thead>

    </table>
            <div class="col-12">
                @if(Model.Order.Id!=0)
            {
            <button type="submit"  class="btn btn-primary" style="width:150px">Update</button>
            }
            else
            {
            <button type="submit"   class="btn btn-primary" style="width:150px">Create</button>
            }
            </a>
            <a asp-controller="Home" asp-action="Index" class="btn btn-primary" style="width:150px">
                Back to list    
            </a>
            </div> 
         </div>
         </div>
         
         </div>
     </div>
    
</form>
@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    <script src="~/js/orderItem.js"></script>
   
    
}